name: Building Kernel

on:
  watch:
    types: [started]
  workflow_dispatch:

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v2

    - name: Checkout zipper (AnyKernel3)
      uses: actions/checkout@v2
      with:
        repository: lemniskett/AnyKernel3
        path: zipper

    - name: Android kernel build
      uses: Abdelhay-Ali/android_kernel_huawei_hi6250_KernelSU@main
      id: build
      env:
        NAME: Dark-Ages-Último
      with:
        arch: arm64
        compiler: gcc/9
        defconfig: Abdelhay_defconfig
        image: Image.gz-dtb

    - name: Copy Image.gz-dtb to AnyKernel3
      run: |
        cp Image.gz-dtb zipper/
        cd zipper
        zip -r9 ../Dark-Ages-KernelSU.zip *

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d-%H%M')" >> "$GITHUB_OUTPUT"

    - name: Tag snapshot
      uses: tvdias/github-tagger@v0.0.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.date.outputs.date }}

    - name: Release build
      uses: ncipollo/release-action@v1
      with:
        artifacts: Dark-Ages-KernelSU.zip
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: ${{ steps.date.outputs.date }}
